alter table orgs enable row level security;
alter table users enable row level security;
alter table teams enable row level security;
alter table inboxes enable row level security;
alter table customers enable row level security;
alter table tickets enable row level security;
alter table threads enable row level security;
alter table messages enable row level security;
alter table attachments enable row level security;
alter table outbox enable row level security;
alter table vector_documents enable row level security;
alter table audit_events enable row level security;
alter table secrets enable row level security;
alter table ai_logs enable row level security;
alter table templates enable row level security;
alter table idempotency_keys enable row level security;
alter table billing_usage enable row level security;

create policy org_isolation_orgs on orgs using (id::text = (current_setting('request.jwt.claims', true)::jsonb->>'org_id'));
create policy org_isolation_users on users using (org_id::text = (current_setting('request.jwt.claims', true)::jsonb->>'org_id'));
create policy org_isolation_teams on teams using (org_id::text = (current_setting('request.jwt.claims', true)::jsonb->>'org_id'));
create policy org_isolation_inboxes on inboxes using (org_id::text = (current_setting('request.jwt.claims', true)::jsonb->>'org_id'));
create policy org_isolation_customers on customers using (org_id::text = (current_setting('request.jwt.claims', true)::jsonb->>'org_id'));
create policy org_isolation_tickets on tickets using (org_id::text = (current_setting('request.jwt.claims', true)::jsonb->>'org_id'));
create policy org_isolation_threads on threads using (org_id::text = (current_setting('request.jwt.claims', true)::jsonb->>'org_id'));
create policy org_isolation_messages on messages using (org_id::text = (current_setting('request.jwt.claims', true)::jsonb->>'org_id'));
create policy org_isolation_attachments on attachments using (org_id::text = (current_setting('request.jwt.claims', true)::jsonb->>'org_id'));
create policy org_isolation_outbox on outbox using (org_id::text = (current_setting('request.jwt.claims', true)::jsonb->>'org_id'));
create policy org_isolation_vector_documents on vector_documents using (org_id::text = (current_setting('request.jwt.claims', true)::jsonb->>'org_id'));
create policy org_isolation_audit_events on audit_events using (org_id::text = (current_setting('request.jwt.claims', true)::jsonb->>'org_id'));
create policy org_isolation_secrets on secrets using (org_id::text = (current_setting('request.jwt.claims', true)::jsonb->>'org_id'));
create policy org_isolation_ai_logs on ai_logs using (org_id::text = (current_setting('request.jwt.claims', true)::jsonb->>'org_id'));
create policy org_isolation_templates on templates using (org_id::text = (current_setting('request.jwt.claims', true)::jsonb->>'org_id'));
create policy org_isolation_idempotency on idempotency_keys using (org_id::text = (current_setting('request.jwt.claims', true)::jsonb->>'org_id'));
create policy org_isolation_billing on billing_usage using (org_id::text = (current_setting('request.jwt.claims', true)::jsonb->>'org_id'));
